[package]
name = "application_3418fa18"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_3418fa18"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../workspace_hack" }
