[package]
name = "application_6e40e01f"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_6e40e01f"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../workspace_hack" }
