[package]
name = "application_ca963e92"
version = "0.1.0"
edition = "2024"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_ca963e92"

[dependencies]
app_ca963e92 = { version = "0.1", path = "..", default-features = false }
http = { version = "1", default-features = false }
hyper = { version = "1", default-features = false }
matchit = { version = "0.9", default-features = false }
pavex = { version = "0.2", path = "../../../../../runtime/pavex", default-features = false }
serde = { version = "1", default-features = false }
thiserror = { version = "2", default-features = false }
