[default]
extend-words = { befores = "befores", bimap = "bimap" }
extend-ignore-words-re = ["\\b[a-zA-Z]{2}\\b"]

[files]
extend-exclude = ["**/expectations/*", "**/generated_app/**", "diagnostics.dot"]
