[package]
name = "application_59d05850"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_59d05850"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../workspace_hack" }
