[package]
name = "application_c2e83ed5"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_c2e83ed5"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../workspace_hack" }
