[package]
name = "app_blueprint"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/bin.rs"
name = "bp"

[dependencies]
anyhow = "1"
pavex_builder = { path = "../../../libs/pavex_builder" }
pavex_cli_client = { path = "../../../libs/pavex_cli_client" }
cargo_px_env = "0.1"
pavex_runtime = { path = "../../../libs/pavex_runtime" }