[package]
name = "application_46ab7f5d"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_46ab7f5d"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../workspace_hack" }
