[package]
name = "application_8b77b4be"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_8b77b4be"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../workspace_hack" }
