[package]
name = "application_6c44cec0"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_6c44cec0"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../../workspace_hack" }
