[project]
name = "md_slash"
version = "0.1.0"
readme = "README.md"
description = "MkDocs extension to convert trailing slashes to <br>"
# The Python version used by the mkdocs-material Docker image
requires-python = ">=3.11"
dependencies = ["Markdown"]

[project.entry-points."markdown.extensions"]
trailing_slash = "md_slash:makeExtension"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
