[package]
name = "mw_core_server_sdk"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "mw_core"

[dependencies]
mw_core = { version = "0.1.0", path = "..", package = "mw_core" }
http = { version = "1.0.0", package = "http" }
hyper = { version = "1.1.0", package = "hyper" }
matchit = { version = "0.7.3", git = "https://github.com/ibraheemdev/matchit", branch = "master", package = "matchit" }
pavex = { version = "0.1.0", path = "../../../../../../libs/pavex", package = "pavex" }
thiserror = { version = "1.0.51", package = "thiserror" }
