[package]
name = "application_67306117"
version = "0.1.0"
edition = "2021"

[package.metadata.px.generate]
generator_type = "cargo_workspace_binary"
generator_name = "app_67306117"

[dependencies]
workspace_hack = { version = "0.1", path = "../../../workspace_hack" }
