# We don't want to include this generator in
# the "root" workspace
[workspace]

[package]
name = "tutorial_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
fs-err = "2.11.0"
anyhow = "1.0.75"
serde_yaml = "0.9.27"
serde_path_to_error = "0.1"
serde = { version = "1", features = ["derive"] }
run_script = "0.10"
similar = { version = "2.3", features = ["inline"] }
console = "0.15.1"
camino = { version = "1", features = ["serde1"] }
globwalk = "0.9.0"
tempfile = "3.8.1"
pathdiff = "0.2.1"
