name: Deploy documentation

on:
  push:
    branches:
      - main
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: Build API reference
        run: |
          cargo api_ref
      - name: Copy API reference files
        run: |
          mkdir -p docs/api_reference
          cp -r target/doc/* docs/api_reference
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python dependencies
        run: uv sync --locked
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "ci@pavex.dev"
          git fetch origin gh-pages:gh-pages || true
      - name: Update unstable documentation
        if: github.ref == 'refs/heads/main'
        run: |
          uv run mike deploy --push --allow-empty unstable
      - name: Update release documentation (tag -> x.y.x)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG#v}"
          VERSION="${TAG%.*}.x" # Deploy `0.2.7` under `0.2.x`
          uv run mike deploy --push --update-aliases "$VERSION" latest
